//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatesDaily
    {
        public Nullable<System.DateTime> date { get; set; }
        public string state { get; set; }
        public Nullable<int> positive { get; set; }
        public string probableCases { get; set; }
        public string negative { get; set; }
        public string pending { get; set; }
        public string totalTestResultsSource { get; set; }
        public Nullable<int> totalTestResults { get; set; }
        public Nullable<int> hospitalizedCurrently { get; set; }
        public Nullable<int> hospitalizedCumulative { get; set; }
        public string inIcuCurrently { get; set; }
        public string inIcuCumulative { get; set; }
        public Nullable<int> onVentilatorCurrently { get; set; }
        public string onVentilatorCumulative { get; set; }
        public string recovered { get; set; }
        public Nullable<System.DateTime> lastUpdateEt { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public string checkTimeEt { get; set; }
        public Nullable<int> death { get; set; }
        public Nullable<int> hospitalized { get; set; }
        public string hospitalizedDischarged { get; set; }
        public Nullable<System.DateTime> dateChecked { get; set; }
        public Nullable<int> totalTestsViral { get; set; }
        public Nullable<int> positiveTestsViral { get; set; }
        public Nullable<int> negativeTestsViral { get; set; }
        public string positiveCasesViral { get; set; }
        public string deathConfirmed { get; set; }
        public string deathProbable { get; set; }
        public string totalTestEncountersViral { get; set; }
        public string totalTestsPeopleViral { get; set; }
        public string totalTestsAntibody { get; set; }
        public string positiveTestsAntibody { get; set; }
        public string negativeTestsAntibody { get; set; }
        public string totalTestsPeopleAntibody { get; set; }
        public string positiveTestsPeopleAntibody { get; set; }
        public string negativeTestsPeopleAntibody { get; set; }
        public string totalTestsPeopleAntigen { get; set; }
        public string positiveTestsPeopleAntigen { get; set; }
        public string totalTestsAntigen { get; set; }
        public string positiveTestsAntigen { get; set; }
        public Nullable<int> fips { get; set; }
        public string positiveIncrease { get; set; }
        public string negativeIncrease { get; set; }
        public Nullable<int> total { get; set; }
        public string totalTestResultsIncrease { get; set; }
        public Nullable<int> posNeg { get; set; }
        public string dataQualityGrade { get; set; }
        public string deathIncrease { get; set; }
        public string hospitalizedIncrease { get; set; }
        public string hash { get; set; }
        public string commercialScore { get; set; }
        public string negativeRegularScore { get; set; }
        public string negativeScore { get; set; }
        public string positiveScore { get; set; }
        public string score { get; set; }
        public string grade { get; set; }
        public int Id { get; set; }
    }
}
