//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsDaily
    {
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> states { get; set; }
        public Nullable<int> positive { get; set; }
        public Nullable<int> negative { get; set; }
        public Nullable<int> pending { get; set; }
        public Nullable<int> hospitalizedCurrently { get; set; }
        public Nullable<int> hospitalizedCumulative { get; set; }
        public Nullable<int> inIcuCurrently { get; set; }
        public Nullable<int> inIcuCumulative { get; set; }
        public Nullable<int> onVentilatorCurrently { get; set; }
        public Nullable<int> onVentilatorCumulative { get; set; }
        public string dateChecked { get; set; }
        public Nullable<int> death { get; set; }
        public Nullable<int> hospitalized { get; set; }
        public Nullable<int> totalTestResults { get; set; }
        public string lastModified { get; set; }
        public string recovered { get; set; }
        public string total { get; set; }
        public string posNeg { get; set; }
        public Nullable<int> deathIncrease { get; set; }
        public Nullable<int> hospitalizedIncrease { get; set; }
        public Nullable<int> negativeIncrease { get; set; }
        public Nullable<int> positiveIncrease { get; set; }
        public Nullable<int> totalTestResultsIncrease { get; set; }
        public string hash { get; set; }
        public int Id { get; set; }
    }
}
